name: driver_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  hive_flutter: ^1.1.0
  pinput: ^2.2.31
  firebase_core: ^2.7.1
  json_annotation: ^4.8.0
  dio: ^5.0.2
  flutter_secure_storage: ^8.0.0
  flutter_credit_card: ^3.0.6
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  http: ^0.13.5
  google_maps_flutter: ^2.2.5
  progress_indicators: ^1.0.0
  intl: ^0.18.0
  firebase_database: ^10.0.15
  flutter_polyline_points: ^1.0.0
  flutter_phone_direct_caller: ^2.1.1
  hive_generator: ^2.0.0
  flutter_svg: ^2.0.4
  google_sign_in: ^6.0.2
  firebase_auth: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
